onerror {resume}
quietly virtual signal -install /tb_irail/m2s010_som_0 { (context /tb_irail/m2s010_som_0 )(CommsFPGA_top_0/ID_RES & CommsFPGA_top_0/OTHERS_NODE & CommsFPGA_top_0/CAMERA_NODE & m2s010_som_sb_0/SPI_1_CLK & m2s010_som_sb_0/SPI_1_DI_CAM & m2s010_som_sb_0/SPI_1_DI_OTH & m2s010_som_sb_0/SPI_1_DI & m2s010_som_sb_0/SPI_1_DO_CAM & m2s010_som_sb_0/SPI_1_DO_OTH & m2s010_som_sb_0/SPI_1_SS0_CAM & m2s010_som_sb_0/SPI_1_SS0_OTH )} SPI_1
quietly virtual signal -install /tb_irail/m2s010_som_0/CommsFPGA_top_0 { (context /tb_irail/m2s010_som_0/CommsFPGA_top_0 )(APB3_ADDR & APB3_CLK & APB3_ENABLE &APB3_RDATA & APB3_READY & APB3_SEL &APB3_WDATA & APB3_WRITE )} APB_BUS
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_CCC_0/GL1_INST/A
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_CCC_0/GL1_INST/Y
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_CCC_0/GL0_INST/A
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_CCC_0/GL0_INST/Y
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rst
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/clk16x
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/APB3_RESET
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/APB3_CLK
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/APB3_ADDR
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/APB3_WDATA
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/write_reg_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_packet_complt
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_packet_complt
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/TX_FIFO_UNDERRUN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/TX_FIFO_OVERFLOW
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/RX_FIFO_UNDERRUN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/RX_FIFO_OVERFLOW
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/col_detect
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_CRC_error
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/int_mask_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/int_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/INT
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_packet_complt_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_packet_avail_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_FIFO_UNDERRUN_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_FIFO_OVERFLOW_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_FIFO_UNDERRUN_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_FIFO_OVERFLOW_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/col_detect_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/int_reg_clr
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/rx_CRC_error_int
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_packet_complt_d
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/INTERRUPT_INST/tx_packet_complt_toClk16x
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/reset
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/clk
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_FIFO_DIN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_FIFO_Empty
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/manches_in_dly
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/sample
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/idle_line
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/rx_packet_end
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/clk1x_enable
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/packet_avail
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/rx_packet_avail
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/rx_packet_end_all
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_EarlyTerm
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_FIFO_Empty_s
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_EarlyTerm_s
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/irx_packet_end_all
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/start_bit_cntr
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/start_bit_mask
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/AFE_RX_STATE
add wave -noupdate /tb_irail/m2s010_som_0/MANCHESTER_IN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/MANCHESTER_IN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/START_BYTE_SYMBOL
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rst
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/clk16x
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/manches_in_dly
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_FIFO_TxColDetDis_wr_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_FIFO_wr_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_FIFO_DIN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_FIFO_DIN_pipe
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_FIFO_Empty
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/MANCHESTER_IN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/MANCH_OUT_P
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/consumer_type1_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/consumer_type2_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/consumer_type3_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/consumer_type4_reg
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/internal_loopback
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/TX_collision_detect
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_crc_Byte_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_packet_avail
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_packet_end
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_packet_complt
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_CRC_error
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_EarlyTerm
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/tx_col_detect_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/TX_Enable
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/clk1x_enable
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/imanches_in_dly
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/sampler_clk1x_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/irx_center_sample
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/idle_line
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/packet_avail
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/rx_packet_end_all
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/iRX_FIFO_DIN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/iRX_EarlyTerm
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/iRX_FIFO_wr_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/irx_packet_end
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/irx_packet_complt
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/RX_IDLE_LINE_CNTR_MAX
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/ReadFIFO_Write_SM_PROC/ReadFIFO_WR_STATE
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/ReadFIFO_Write_SM_PROC/rx_byte_cntr
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/ReadFIFO_Write_SM_PROC/rx_byte_cntr
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/AFE_RX_STATE
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/AFE_RX_STATE_MACHINE/RX_FIFO_DIN
add wave -noupdate /tb_irail/m2s010_som_0_MANCH_OUT_N
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_ENCODER_INST/MANCHESTER_OUT
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/MANCHESTER_DECODER_INST/MANCHESTER_DECODER_ADAPTER_INST/MANCHESTER_IN
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/APB3_RDATA
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/APB3_WRITE
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/APB3_WDATA
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/APB3_ADDR
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/FIFOS_INST/TRANSMIT_FIFO/EMPTY
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/APB3_CLK
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/control_reg_en
add wave -noupdate /tb_irail/m2s010_som_0/CommsFPGA_top_0/PROCESSOR_INTERFACE_INST/control_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 6} {34111909474726 fs} 0} {{Cursor 7} {32269465602958 fs} 0} {{Cursor 8} {32272435873570 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 234
configure wave -valuecolwidth 99
configure wave -justifyvalue right
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {34106573573648 fs} {34114851321328 fs}
